"""Added ListShare and relationships

Revision ID: 245afea7ab19
Revises: 750904daeeea
Create Date: 2025-05-13 23:51:01.969918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245afea7ab19'
down_revision = '750904daeeea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_share', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('_list_user_uc', ['list_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_share', schema=None) as batch_op:
        batch_op.drop_constraint('_list_user_uc', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
