"""empty message

Revision ID: 43a55613e91b
Revises: 245afea7ab19
Create Date: 2025-05-14 00:08:51.618308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a55613e91b'
down_revision = '245afea7ab19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            constraint_name="fk_created_by_user",  # ✅ Explicit name
            referent_table="user",
            local_cols=["created_by"],
            remote_cols=["id"]
                )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
