"""Add user_id to GroceryItem

Revision ID: 750904daeeea
Revises: 82b75704e461
Create Date: 2025-05-13 23:03:17.605350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750904daeeea'
down_revision = '82b75704e461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
